analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  
  errors:
    # treat missing required parameters as an error
    missing_required_param: error
    # treat missing returns as an error
    missing_return: error
    # allow having TODOs in the code
    todo: ignore
    # Helps catch errors related to deprecation
    deprecated_member_use_from_same_package: error

linter:
  rules:
    # Prevent potential bugs
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    
    # Code style
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    
    # Formatting
    - lines_longer_than_80_chars