name: tasktimetracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Networking
  dio: ^5.3.2
  connectivity_plus: ^4.0.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Dependency Injection
  get_it: ^7.6.0

  # Functional Programming & Error Handling
  dartz: ^0.10.1

  # Logging
  logger: ^2.0.2

  # Date Handling
  intl: ^0.18.1

  #Kanbon board
  flutter_boardview_kanban: ^1.0.1
  appflowy_board: ^0.1.2
  uuid: ^4.5.1
  flutter_timer_countdown: ^1.0.7
  stop_watch_timer: ^3.2.1

  #database
  hive_generator: ^2.0.1
  path_provider: ^2.1.5
  
  freezed_annotation: ^2.4.4
  injectable: ^2.0.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mocktail: ^1.0.0
  bloc_test: ^9.1.4
  mockito: ^5.4.4

  

  # Code Generation
  build_runner: ^2.4.6
  freezed: ^2.5.7

  
  # Static Analysis
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
