// Mocks generated by Mockito 5.4.4 from annotations
// in tasktimetracker/test/features/task_management/presentation/bloc/task_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tasktimetracker/core/error/failures.dart' as _i7;
import 'package:tasktimetracker/core/usecases/usecase.dart' as _i9;
import 'package:tasktimetracker/features/task_management/domain/entities/task.dart'
    as _i6;
import 'package:tasktimetracker/features/task_management/domain/repositories/todoist_local_repository.dart'
    as _i3;
import 'package:tasktimetracker/features/task_management/domain/repositories/todoist_remote_repository.dart'
    as _i4;
import 'package:tasktimetracker/features/task_management/domain/usecases/get_tasks_usecase.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTodoistLocalRepository_1 extends _i1.SmartFake
    implements _i3.TodoistLocalRepository {
  _FakeTodoistLocalRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTodoistRemoteRepository_2 extends _i1.SmartFake
    implements _i4.TodoistRemoteRepository {
  _FakeTodoistRemoteRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TodoistLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoistLocalRepository extends _i1.Mock
    implements _i3.TodoistLocalRepository {
  MockTodoistLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> addTask(_i6.TaskEntity? task) => (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [task],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTask(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [taskId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTask(_i6.TaskEntity? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.TaskEntity?> getTask(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #getTask,
          [taskId],
        ),
        returnValue: _i5.Future<_i6.TaskEntity?>.value(),
      ) as _i5.Future<_i6.TaskEntity?>);

  @override
  _i5.Future<List<_i6.TaskEntity>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: _i5.Future<List<_i6.TaskEntity>>.value(<_i6.TaskEntity>[]),
      ) as _i5.Future<List<_i6.TaskEntity>>);
}

/// A class which mocks [TodoistRemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoistRemoteRepository extends _i1.Mock
    implements _i4.TodoistRemoteRepository {
  MockTodoistRemoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i7.Failure, List<_i6.TaskEntity>>> getTasks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasks,
          [],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i7.Failure, List<_i6.TaskEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i6.TaskEntity>>(
          this,
          Invocation.method(
            #getTasks,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, List<_i6.TaskEntity>>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i6.TaskEntity>> createTask(
          _i6.TaskEntity? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i6.TaskEntity>>.value(
            _FakeEither_0<_i7.Failure, _i6.TaskEntity>(
          this,
          Invocation.method(
            #createTask,
            [task],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i6.TaskEntity>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, void>> deleteTask(String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [taskId],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #deleteTask,
            [taskId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i6.TaskEntity>> updateTask(
          _i6.TaskEntity? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i6.TaskEntity>>.value(
            _FakeEither_0<_i7.Failure, _i6.TaskEntity>(
          this,
          Invocation.method(
            #updateTask,
            [task],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i6.TaskEntity>>);
}

/// A class which mocks [GetTasksUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTasksUseCase extends _i1.Mock implements _i8.GetTasksUseCase {
  MockGetTasksUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TodoistLocalRepository get localRepository => (super.noSuchMethod(
        Invocation.getter(#localRepository),
        returnValue: _FakeTodoistLocalRepository_1(
          this,
          Invocation.getter(#localRepository),
        ),
      ) as _i3.TodoistLocalRepository);

  @override
  _i4.TodoistRemoteRepository get remoteRepository => (super.noSuchMethod(
        Invocation.getter(#remoteRepository),
        returnValue: _FakeTodoistRemoteRepository_2(
          this,
          Invocation.getter(#remoteRepository),
        ),
      ) as _i4.TodoistRemoteRepository);

  @override
  _i5.Future<_i2.Either<_i7.Failure, List<_i6.TaskEntity>>> call(
          _i9.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i7.Failure, List<_i6.TaskEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i6.TaskEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, List<_i6.TaskEntity>>>);
}
