name: Flutter CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for specified branches
  push:
    branches: [ main, develop ]
  # Allows manual triggering of the workflow
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  # Job for testing and building the app
  test_and_build:
    # Runner type
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      
      # Setup Java (required for Flutter)
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      # Setup Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
      
      # Enable Flutter web
      - name: Enable Flutter web
        run: flutter config --enable-web
      
      # Get dependencies
      - name: Install dependencies
        run: flutter pub get
      
      # Run code analysis
      - name: Analyze code
        run: flutter analyze
      
      # Run unit tests
      - name: Run unit tests
        run: flutter test
      
      # Build Android APK
      - name: Build Android APK
        run: flutter build apk
      
      # Build iOS app (on macOS runners)
      - name: Build iOS app
        run: flutter build ios --release --no-codesign
      
      # Build Web app
      - name: Build Web app
        run: flutter build web

  # Deployment job (optional)
  deploy:
    needs: test_and_build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      # Example: Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: your-firebase-project-id
