name: Flutter CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      # Setup Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true
      
      # Verify installation
      - name: Verify Flutter installation
        run: |
          flutter --version
          dart --version
      
      # Get dependencies
      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub upgrade
      
      # Generate code for Freezed and other code generators
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
      
      # Run code analysis
      - name: Analyze code
        run: flutter analyze
      
      # Run unit tests
      - name: Run unit tests
        run: flutter test
      
      # Build Android APK
      - name: Build Android APK
        run: flutter build apk --release
      
      # Build Web app
      - name: Build Web app
        run: flutter build web
      
      # Optional: Upload build artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk